# Stage 1: Build the application
FROM maven:3.9-eclipse-temurin-21-alpine AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package

# Stage 2: Run the application
FROM eclipse-temurin:21.0.9_10-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar ./tease-broker.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "./tease-broker.jar"]



